packages:
  - packages/*
  - examples/*

catalogMode: prefer

catalog:
  "@alcalzone/ansi-tokenize": ^0.3.0
  "@types/node": ^24.12.4
  ansi-escapes: ^7.3.0
  chalk: ^5.6.2
  is-in-ci: ^2.0.0
  patch-console: ^2.0.0
  solid-js: ^1.9.14
  string-width: ^8.0.0
  strip-ansi: ^7.2.0
  terminal-size: ^4.0.1
  tsx: ^4.22.0
  typescript: ^5
  vite: 8.1.0
  vite-plugin-solid: ^2.11.12
  vite-plus: ^0.1.22
  vitest: ^4.1.5

overrides:
  vite: "catalog:"
  "@types/node": "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - solid-js@1.9.14
